CREATE TRIGGER decrease_stock
  AFTER INSERT ON ORDER_CONTAINS
  BEGIN
    UPDATE BOOK SET stock = stock - NEW.quantity WHERE BOOK.ISBN = NEW.ISBN;
  END;

CREATE TRIGGER order_time
  AFTER INSERT ON ORDER_TABLE
  BEGIN
    UPDATE ORDER_TABLE SET date = DATETIME('NOW') WHERE ORDER_TABLE.onum = NEW.onum;
    UPDATE ORDER_TABLE SET tracking_num = abs(random()) WHERE ORDER_TABLE.onum = NEW.onum;
  END;

CREATE TRIGGER reorder_check
  AFTER UPDATE ON BOOK WHEN New.stock < 2
  BEGIN
    SELECT SUM(ORDER_CONTAINS.quantity) FROM ORDER_CONTAINS JOIN ORDER_TABLE ON ORDER_CONTAINS.onum = ORDER_TABLE.onum WHERE ORDER_CONTAINS.ISBN = New.ISBN AND ORDER_TABLE.date = ;
  END;
